version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "github.com/infobloxopen/infoblox-nios-go-client"
      - dependency-name: "github.com/infobloxopen/universal-ddi-go-client"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
