package infoblox

import (
	ibclient "github.com/infobloxopen/infoblox-go-client/v2"
	"github.com/infobloxopen/infoblox-go-client/v2/utils"
)

var testCasePtrRecordExpectedData00 = map[string]*ibclient.RecordPTR{
	"infoblox_ptr_record.rec1": {
		View:     "default",
		Ipv4Addr: utils.StringPtr("10.0.0.1"),
		Ipv6Addr: nil,
		Name:     utils.StringPtr("1.0.0.10.in-addr.arpa"),
		PtrdName: utils.StringPtr("ptr-target1.example1.org"),
		Zone:     "0.0.10.in-addr.arpa",
		UseTtl:   utils.BoolPtr(false),
		Ttl:      nil,
		Comment:  nil,
		Ea:       ibclient.EA{},
	},
	"infoblox_ptr_record.rec2": {
		View:     "default",
		Ipv4Addr: utils.StringPtr("10.0.0.2"),
		Ipv6Addr: nil,
		Name:     utils.StringPtr("2.0.0.10.in-addr.arpa"),
		PtrdName: utils.StringPtr("ptr-target2.example1.org"),
		Zone:     "0.0.10.in-addr.arpa",
		UseTtl:   utils.BoolPtr(false),
		Ttl:      nil,
		Comment:  nil,
		Ea:       ibclient.EA{},
	},
	"infoblox_ptr_record.rec3": {
		View:     "default",
		Ipv4Addr: nil,
		Ipv6Addr: nil,
		Name:     utils.StringPtr("ptr-rec3.example1.org"),
		PtrdName: utils.StringPtr("ptr-target3.example1.org"),
		Zone:     "example1.org",
		UseTtl:   utils.BoolPtr(false),
		Ttl:      nil,
		Comment:  nil,
		Ea:       ibclient.EA{},
	},
	"infoblox_ptr_record.rec4": {
		View:     "default",
		Ipv4Addr: utils.StringPtr("10.0.0.202"),
		Ipv6Addr: nil,
		Name:     utils.StringPtr("202.0.0.10.in-addr.arpa"),
		PtrdName: utils.StringPtr("ptr-target4.example1.org"),
		Zone:     "0.0.10.in-addr.arpa",
		UseTtl:   utils.BoolPtr(false),
		Ttl:      nil,
		Comment:  nil,
		Ea:       ibclient.EA{},
	},
	"infoblox_ptr_record.rec5": {
		View:     "default",
		Ipv4Addr: nil,
		Ipv6Addr: utils.StringPtr("2002:1f93::5"),
		Name:     utils.StringPtr("5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa"),
		PtrdName: utils.StringPtr("ptr-target5.example1.org"),
		Zone:     "0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(300),
		Comment:  utils.StringPtr("workstation #5"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec6": {
		View:     "default",
		Ipv4Addr: nil,
		Ipv6Addr: utils.StringPtr("2002:1f93::6"),
		Name:     utils.StringPtr("6.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa"),
		PtrdName: utils.StringPtr("ptr-target6.example1.org"),
		Zone:     "0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(30),
		Comment:  utils.StringPtr("workstation #6"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec7": {
		View:     "default",
		Ipv4Addr: nil,
		Ipv6Addr: utils.StringPtr("2002:1f93::c9"),
		Name:     utils.StringPtr("9.c.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa"),
		PtrdName: utils.StringPtr("ptr-target7.example1.org"),
		Zone:     "0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(30),
		Comment:  utils.StringPtr("workstation #7"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec8": {
		View:     "default",
		Ipv4Addr: nil,
		Ipv6Addr: nil,
		Name:     utils.StringPtr("ptr-rec8.example1.org"),
		PtrdName: utils.StringPtr("ptr-target8.example1.org"),
		Zone:     "example1.org",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(301),
		Comment:  utils.StringPtr("workstation #8"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec9": {
		View:     "nondefault_dnsview1",
		Ipv4Addr: nil,
		Ipv6Addr: utils.StringPtr("2002:1f93::9"),
		Name:     utils.StringPtr("9.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa"),
		PtrdName: utils.StringPtr("ptr-target9.example2.org"),
		Zone:     "0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(300),
		Comment:  utils.StringPtr("workstation #9"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec10": {
		View:     "nondefault_dnsview1",
		Ipv4Addr: nil,
		Ipv6Addr: utils.StringPtr("2002:1f93::a"),
		Name:     utils.StringPtr("a.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa"),
		PtrdName: utils.StringPtr("ptr-target10.example2.org"),
		Zone:     "0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(30),
		Comment:  utils.StringPtr("workstation #10"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec11": {
		View:     "nondefault_dnsview1",
		Ipv4Addr: nil,
		Ipv6Addr: nil,
		Name:     utils.StringPtr("ptr-rec11.example2.org"),
		PtrdName: utils.StringPtr("ptr-target11.example2.org"),
		Zone:     "example2.org",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(301),
		Comment:  utils.StringPtr("workstation #11"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec12": {
		View:     "nondefault_dnsview1",
		Ipv4Addr: utils.StringPtr("10.0.0.203"),
		Ipv6Addr: nil,
		Name:     utils.StringPtr("203.0.0.10.in-addr.arpa"),
		PtrdName: utils.StringPtr("ptr-target12.example2.org"),
		Zone:     "10.in-addr.arpa",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(30),
		Comment:  utils.StringPtr("workstation #12"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec13": {
		View:     "nondefault_dnsview2",
		Ipv4Addr: nil,
		Ipv6Addr: utils.StringPtr("2002:1f93::c9"),
		Name:     utils.StringPtr("9.c.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa"),
		PtrdName: utils.StringPtr("ptr-target13.example4.org"),
		Zone:     "0.0.0.0.0.0.0.0.3.9.f.1.2.0.0.2.ip6.arpa",
		UseTtl:   utils.BoolPtr(true),
		Ttl:      utils.Uint32Ptr(30),
		Comment:  utils.StringPtr("workstation #13"),
		Ea:       ibclient.EA{"Location": "the main office"},
	},
	"infoblox_ptr_record.rec14": {
		View:     "default",
		Ipv4Addr: utils.StringPtr("10.0.0.14"),
		Ipv6Addr: nil,
		Name:     utils.StringPtr("14.0.0.10.in-addr.arpa"),
		PtrdName: utils.StringPtr("ptr-target14.example1.org"),
		Zone:     "0.0.10.in-addr.arpa",
		UseTtl:   utils.BoolPtr(false),
		Ttl:      nil,
		Comment:  nil,
		Ea:       ibclient.EA{},
	},
}
