package dhcp

import "github.com/infobloxopen/terraform-provider-infoblox/internal/core"

// FixedaddressNIOSFieldMap maps infoblox model fields to NIOS struct fields
var FixedaddressNIOSFieldMap = map[string]string{
	"Id":                                  "Ref",
	"NIOS.AgentCircuitId":                 "AgentCircuitId",
	"NIOS.AgentRemoteId":                  "AgentRemoteId",
	"NIOS.AllowTelnet":                    "AllowTelnet",
	"NIOS.AlwaysUpdateDns":                "AlwaysUpdateDns",
	"NIOS.Bootfile":                       "Bootfile",
	"NIOS.Bootserver":                     "Bootserver",
	"NIOS.CliCredentials":                 "CliCredentials",
	"NIOS.ClientIdentifierPrependZero":    "ClientIdentifierPrependZero",
	"NIOS.Comment":                        "Comment",
	"NIOS.DdnsDomainname":                 "DdnsDomainname",
	"NIOS.DdnsHostname":                   "DdnsHostname",
	"NIOS.DenyBootp":                      "DenyBootp",
	"NIOS.DeviceDescription":              "DeviceDescription",
	"NIOS.DeviceLocation":                 "DeviceLocation",
	"NIOS.DeviceType":                     "DeviceType",
	"NIOS.DeviceVendor":                   "DeviceVendor",
	"NIOS.DhcpClientIdentifier":           "DhcpClientIdentifier",
	"NIOS.Disable":                        "Disable",
	"NIOS.DisableDiscovery":               "DisableDiscovery",
	"NIOS.EnableDdns":                     "EnableDdns",
	"NIOS.EnableImmediateDiscovery":       "EnableImmediateDiscovery",
	"NIOS.EnablePxeLeaseTime":             "EnablePxeLeaseTime",
	"NIOS.IgnoreDhcpOptionListRequest":    "IgnoreDhcpOptionListRequest",
	"NIOS.Ipv4addr":                       "Ipv4addr.String",
	"NIOS.LogicFilterRules":               "LogicFilterRules",
	"NIOS.Mac":                            "Mac",
	"NIOS.MatchClient":                    "MatchClient",
	"NIOS.MsOptions":                      "MsOptions",
	"NIOS.MsServer":                       "MsServer",
	"NIOS.Name":                           "Name",
	"NIOS.Network":                        "Network",
	"NIOS.NetworkView":                    "NetworkView",
	"NIOS.Nextserver":                     "Nextserver",
	"NIOS.Options":                        "Options",
	"NIOS.PxeLeaseTime":                   "PxeLeaseTime",
	"NIOS.ReservedInterface":              "ReservedInterface",
	"NIOS.RestartIfNeeded":                "RestartIfNeeded",
	"NIOS.Snmp3Credential":                "Snmp3Credential",
	"NIOS.SnmpCredential":                 "SnmpCredential",
	"NIOS.Template":                       "Template",
	"NIOS.UseBootfile":                    "UseBootfile",
	"NIOS.UseBootserver":                  "UseBootserver",
	"NIOS.UseCliCredentials":              "UseCliCredentials",
	"NIOS.UseDdnsDomainname":              "UseDdnsDomainname",
	"NIOS.UseDenyBootp":                   "UseDenyBootp",
	"NIOS.UseEnableDdns":                  "UseEnableDdns",
	"NIOS.UseIgnoreDhcpOptionListRequest": "UseIgnoreDhcpOptionListRequest",
	"NIOS.UseLogicFilterRules":            "UseLogicFilterRules",
	"NIOS.UseMsOptions":                   "UseMsOptions",
	"NIOS.UseNextserver":                  "UseNextserver",
	"NIOS.UseOptions":                     "UseOptions",
	"NIOS.UsePxeLeaseTime":                "UsePxeLeaseTime",
	"NIOS.UseSnmp3Credential":             "UseSnmp3Credential",
	"NIOS.UseSnmpCredential":              "UseSnmpCredential",
	"NIOS.FuncCall":                       "FuncCall",
}

// FixedaddressUDDIFieldMap maps infoblox model fields to UDDI struct fields
var FixedaddressUDDIFieldMap = map[string]string{
	"UDDI.Address":                   "Address",
	"UDDI.Comment":                   "Comment",
	"UDDI.DhcpOptions":               "DhcpOptions",
	"UDDI.DisableDhcp":               "DisableDhcp",
	"UDDI.HeaderOptionFilename":      "HeaderOptionFilename",
	"UDDI.HeaderOptionServerAddress": "HeaderOptionServerAddress",
	"UDDI.HeaderOptionServerName":    "HeaderOptionServerName",
	"UDDI.Hostname":                  "Hostname",
	"UDDI.InheritanceParent":         "InheritanceParent",
	"UDDI.InheritanceSources":        "InheritanceSources",
	"UDDI.IpSpace":                   "IpSpace",
	"UDDI.MatchType":                 "MatchType",
	"UDDI.MatchValue":                "MatchValue",
	"UDDI.Name":                      "Name",
	"UDDI.Parent":                    "Parent",
	"UDDI.Tags":                      "Tags",
}

// TODO: only searchable fields should be included here
// FixedaddressFilterFieldMap maps infoblox filter keys to backend-specific API filter field names
var FixedaddressFilterFieldMap = map[core.BackendType]map[string]string{
	core.BackendNIOS: {
		"id":                                       "_ref",
		"nios.agent_circuit_id":                    "agent_circuit_id",
		"nios.agent_remote_id":                     "agent_remote_id",
		"nios.allow_telnet":                        "allow_telnet",
		"nios.always_update_dns":                   "always_update_dns",
		"nios.bootfile":                            "bootfile",
		"nios.bootserver":                          "bootserver",
		"nios.cli_credentials":                     "cli_credentials",
		"nios.client_identifier_prepend_zero":      "client_identifier_prepend_zero",
		"nios.comment":                             "comment",
		"nios.ddns_domainname":                     "ddns_domainname",
		"nios.ddns_hostname":                       "ddns_hostname",
		"nios.deny_bootp":                          "deny_bootp",
		"nios.device_description":                  "device_description",
		"nios.device_location":                     "device_location",
		"nios.device_type":                         "device_type",
		"nios.device_vendor":                       "device_vendor",
		"nios.dhcp_client_identifier":              "dhcp_client_identifier",
		"nios.disable":                             "disable",
		"nios.disable_discovery":                   "disable_discovery",
		"nios.enable_ddns":                         "enable_ddns",
		"nios.enable_immediate_discovery":          "enable_immediate_discovery",
		"nios.enable_pxe_lease_time":               "enable_pxe_lease_time",
		"nios.ext_attrs":                           "extattrs",
		"nios.ignore_dhcp_option_list_request":     "ignore_dhcp_option_list_request",
		"nios.ipv4addr":                            "ipv4addr",
		"nios.logic_filter_rules":                  "logic_filter_rules",
		"nios.mac":                                 "mac",
		"nios.match_client":                        "match_client",
		"nios.ms_options":                          "ms_options",
		"nios.ms_server":                           "ms_server",
		"nios.name":                                "name",
		"nios.network":                             "network",
		"nios.network_view":                        "network_view",
		"nios.nextserver":                          "nextserver",
		"nios.options":                             "options",
		"nios.pxe_lease_time":                      "pxe_lease_time",
		"nios.reserved_interface":                  "reserved_interface",
		"nios.restart_if_needed":                   "restart_if_needed",
		"nios.snmp3_credential":                    "snmp3_credential",
		"nios.snmp_credential":                     "snmp_credential",
		"nios.template":                            "template",
		"nios.use_bootfile":                        "use_bootfile",
		"nios.use_bootserver":                      "use_bootserver",
		"nios.use_cli_credentials":                 "use_cli_credentials",
		"nios.use_ddns_domainname":                 "use_ddns_domainname",
		"nios.use_deny_bootp":                      "use_deny_bootp",
		"nios.use_enable_ddns":                     "use_enable_ddns",
		"nios.use_ignore_dhcp_option_list_request": "use_ignore_dhcp_option_list_request",
		"nios.use_logic_filter_rules":              "use_logic_filter_rules",
		"nios.use_ms_options":                      "use_ms_options",
		"nios.use_nextserver":                      "use_nextserver",
		"nios.use_options":                         "use_options",
		"nios.use_pxe_lease_time":                  "use_pxe_lease_time",
		"nios.use_snmp3_credential":                "use_snmp3_credential",
		"nios.use_snmp_credential":                 "use_snmp_credential",
	},
	core.BackendUDDI: {
		"uddi.address":                      "address",
		"uddi.comment":                      "comment",
		"uddi.dhcp_options":                 "dhcp_options",
		"uddi.disable_dhcp":                 "disable_dhcp",
		"uddi.header_option_filename":       "header_option_filename",
		"uddi.header_option_server_address": "header_option_server_address",
		"uddi.header_option_server_name":    "header_option_server_name",
		"uddi.hostname":                     "hostname",
		"uddi.inheritance_parent":           "inheritance_parent",
		"uddi.inheritance_sources":          "inheritance_sources",
		"uddi.ip_space":                     "ip_space",
		"uddi.match_type":                   "match_type",
		"uddi.match_value":                  "match_value",
		"uddi.name":                         "name",
		"uddi.parent":                       "parent",
		"uddi.tags":                         "tags",
	},
}
