package dhcp

import "github.com/infobloxopen/terraform-provider-infoblox/internal/core"

// Ipv6sharednetworkNIOSFieldMap maps infoblox model fields to NIOS struct fields
var Ipv6sharednetworkNIOSFieldMap = map[string]string{
	"Id":                              "Ref",
	"NIOS.Comment":                    "Comment",
	"NIOS.DdnsDomainname":             "DdnsDomainname",
	"NIOS.DdnsGenerateHostname":       "DdnsGenerateHostname",
	"NIOS.DdnsServerAlwaysUpdates":    "DdnsServerAlwaysUpdates",
	"NIOS.DdnsTtl":                    "DdnsTtl",
	"NIOS.DdnsUseOption81":            "DdnsUseOption81",
	"NIOS.Disable":                    "Disable",
	"NIOS.DomainName":                 "DomainName",
	"NIOS.DomainNameServers":          "DomainNameServers",
	"NIOS.EnableDdns":                 "EnableDdns",
	"NIOS.LogicFilterRules":           "LogicFilterRules",
	"NIOS.Name":                       "Name",
	"NIOS.NetworkView":                "NetworkView",
	"NIOS.Networks":                   "Networks",
	"NIOS.Options":                    "Options",
	"NIOS.PreferredLifetime":          "PreferredLifetime",
	"NIOS.UpdateDnsOnLeaseRenewal":    "UpdateDnsOnLeaseRenewal",
	"NIOS.UseDdnsDomainname":          "UseDdnsDomainname",
	"NIOS.UseDdnsGenerateHostname":    "UseDdnsGenerateHostname",
	"NIOS.UseDdnsTtl":                 "UseDdnsTtl",
	"NIOS.UseDdnsUseOption81":         "UseDdnsUseOption81",
	"NIOS.UseDomainName":              "UseDomainName",
	"NIOS.UseDomainNameServers":       "UseDomainNameServers",
	"NIOS.UseEnableDdns":              "UseEnableDdns",
	"NIOS.UseLogicFilterRules":        "UseLogicFilterRules",
	"NIOS.UseOptions":                 "UseOptions",
	"NIOS.UsePreferredLifetime":       "UsePreferredLifetime",
	"NIOS.UseUpdateDnsOnLeaseRenewal": "UseUpdateDnsOnLeaseRenewal",
	"NIOS.UseValidLifetime":           "UseValidLifetime",
	"NIOS.ValidLifetime":              "ValidLifetime",
}

// TODO: only searchable fields should be included here
// Ipv6sharednetworkFilterFieldMap maps infoblox filter keys to backend-specific API filter field names
var Ipv6sharednetworkFilterFieldMap = map[core.BackendType]map[string]string{
	core.BackendNIOS: {
		"id":                                   "_ref",
		"nios.comment":                         "comment",
		"nios.ddns_domainname":                 "ddns_domainname",
		"nios.ddns_generate_hostname":          "ddns_generate_hostname",
		"nios.ddns_server_always_updates":      "ddns_server_always_updates",
		"nios.ddns_ttl":                        "ddns_ttl",
		"nios.ddns_use_option81":               "ddns_use_option81",
		"nios.disable":                         "disable",
		"nios.domain_name":                     "domain_name",
		"nios.domain_name_servers":             "domain_name_servers",
		"nios.enable_ddns":                     "enable_ddns",
		"nios.ext_attrs":                       "extattrs",
		"nios.logic_filter_rules":              "logic_filter_rules",
		"nios.name":                            "name",
		"nios.network_view":                    "network_view",
		"nios.networks":                        "networks",
		"nios.options":                         "options",
		"nios.preferred_lifetime":              "preferred_lifetime",
		"nios.update_dns_on_lease_renewal":     "update_dns_on_lease_renewal",
		"nios.use_ddns_domainname":             "use_ddns_domainname",
		"nios.use_ddns_generate_hostname":      "use_ddns_generate_hostname",
		"nios.use_ddns_ttl":                    "use_ddns_ttl",
		"nios.use_ddns_use_option81":           "use_ddns_use_option81",
		"nios.use_domain_name":                 "use_domain_name",
		"nios.use_domain_name_servers":         "use_domain_name_servers",
		"nios.use_enable_ddns":                 "use_enable_ddns",
		"nios.use_logic_filter_rules":          "use_logic_filter_rules",
		"nios.use_options":                     "use_options",
		"nios.use_preferred_lifetime":          "use_preferred_lifetime",
		"nios.use_update_dns_on_lease_renewal": "use_update_dns_on_lease_renewal",
		"nios.use_valid_lifetime":              "use_valid_lifetime",
		"nios.valid_lifetime":                  "valid_lifetime",
	},
}
