package dhcp

import "github.com/infobloxopen/terraform-provider-infoblox/internal/core"

// Ipv6fixedaddressNIOSFieldMap maps infoblox model fields to NIOS struct fields
var Ipv6fixedaddressNIOSFieldMap = map[string]string{
	"Id":                            "Ref",
	"NIOS.AddressType":              "AddressType",
	"NIOS.AllowTelnet":              "AllowTelnet",
	"NIOS.CliCredentials":           "CliCredentials",
	"NIOS.Comment":                  "Comment",
	"NIOS.DeviceDescription":        "DeviceDescription",
	"NIOS.DeviceLocation":           "DeviceLocation",
	"NIOS.DeviceType":               "DeviceType",
	"NIOS.DeviceVendor":             "DeviceVendor",
	"NIOS.Disable":                  "Disable",
	"NIOS.DisableDiscovery":         "DisableDiscovery",
	"NIOS.DomainName":               "DomainName",
	"NIOS.DomainNameServers":        "DomainNameServers",
	"NIOS.Duid":                     "Duid",
	"NIOS.EnableImmediateDiscovery": "EnableImmediateDiscovery",
	"NIOS.Ipv6addr":                 "Ipv6addr.String",
	"NIOS.Ipv6prefix":               "Ipv6prefix",
	"NIOS.Ipv6prefixBits":           "Ipv6prefixBits",
	"NIOS.LogicFilterRules":         "LogicFilterRules",
	"NIOS.MacAddress":               "MacAddress",
	"NIOS.MatchClient":              "MatchClient",
	"NIOS.Name":                     "Name",
	"NIOS.Network":                  "Network",
	"NIOS.NetworkView":              "NetworkView",
	"NIOS.Options":                  "Options",
	"NIOS.PreferredLifetime":        "PreferredLifetime",
	"NIOS.ReservedInterface":        "ReservedInterface",
	"NIOS.RestartIfNeeded":          "RestartIfNeeded",
	"NIOS.Snmp3Credential":          "Snmp3Credential",
	"NIOS.SnmpCredential":           "SnmpCredential",
	"NIOS.Template":                 "Template",
	"NIOS.UseCliCredentials":        "UseCliCredentials",
	"NIOS.UseDomainName":            "UseDomainName",
	"NIOS.UseDomainNameServers":     "UseDomainNameServers",
	"NIOS.UseLogicFilterRules":      "UseLogicFilterRules",
	"NIOS.UseOptions":               "UseOptions",
	"NIOS.UsePreferredLifetime":     "UsePreferredLifetime",
	"NIOS.UseSnmp3Credential":       "UseSnmp3Credential",
	"NIOS.UseSnmpCredential":        "UseSnmpCredential",
	"NIOS.UseValidLifetime":         "UseValidLifetime",
	"NIOS.ValidLifetime":            "ValidLifetime",
	"NIOS.FuncCall":                 "FuncCall",
}

// Ipv6fixedaddressUDDIFieldMap maps infoblox model fields to UDDI struct fields
var Ipv6fixedaddressUDDIFieldMap = map[string]string{
	"UDDI.Address":            "Address",
	"UDDI.Comment":            "Comment",
	"UDDI.DhcpOptions":        "DhcpOptions",
	"UDDI.DisableDhcp":        "DisableDhcp",
	"UDDI.Hostname":           "Hostname",
	"UDDI.InheritanceParent":  "InheritanceParent",
	"UDDI.InheritanceSources": "InheritanceSources",
	"UDDI.IpSpace":            "IpSpace",
	"UDDI.MatchType":          "MatchType",
	"UDDI.MatchValue":         "MatchValue",
	"UDDI.Name":               "Name",
	"UDDI.Parent":             "Parent",
	"UDDI.Tags":               "Tags",
}

// TODO: only searchable fields should be included here
// Ipv6fixedaddressFilterFieldMap maps infoblox filter keys to backend-specific API filter field names
var Ipv6fixedaddressFilterFieldMap = map[core.BackendType]map[string]string{
	core.BackendNIOS: {
		"id":                              "_ref",
		"nios.address_type":               "address_type",
		"nios.allow_telnet":               "allow_telnet",
		"nios.cli_credentials":            "cli_credentials",
		"nios.comment":                    "comment",
		"nios.device_description":         "device_description",
		"nios.device_location":            "device_location",
		"nios.device_type":                "device_type",
		"nios.device_vendor":              "device_vendor",
		"nios.disable":                    "disable",
		"nios.disable_discovery":          "disable_discovery",
		"nios.domain_name":                "domain_name",
		"nios.domain_name_servers":        "domain_name_servers",
		"nios.duid":                       "duid",
		"nios.enable_immediate_discovery": "enable_immediate_discovery",
		"nios.ext_attrs":                  "extattrs",
		"nios.ipv6addr":                   "ipv6addr",
		"nios.ipv6prefix":                 "ipv6prefix",
		"nios.ipv6prefix_bits":            "ipv6prefix_bits",
		"nios.logic_filter_rules":         "logic_filter_rules",
		"nios.mac_address":                "mac_address",
		"nios.match_client":               "match_client",
		"nios.name":                       "name",
		"nios.network":                    "network",
		"nios.network_view":               "network_view",
		"nios.options":                    "options",
		"nios.preferred_lifetime":         "preferred_lifetime",
		"nios.reserved_interface":         "reserved_interface",
		"nios.restart_if_needed":          "restart_if_needed",
		"nios.snmp3_credential":           "snmp3_credential",
		"nios.snmp_credential":            "snmp_credential",
		"nios.template":                   "template",
		"nios.use_cli_credentials":        "use_cli_credentials",
		"nios.use_domain_name":            "use_domain_name",
		"nios.use_domain_name_servers":    "use_domain_name_servers",
		"nios.use_logic_filter_rules":     "use_logic_filter_rules",
		"nios.use_options":                "use_options",
		"nios.use_preferred_lifetime":     "use_preferred_lifetime",
		"nios.use_snmp3_credential":       "use_snmp3_credential",
		"nios.use_snmp_credential":        "use_snmp_credential",
		"nios.use_valid_lifetime":         "use_valid_lifetime",
		"nios.valid_lifetime":             "valid_lifetime",
	},
	core.BackendUDDI: {
		"uddi.address":             "address",
		"uddi.comment":             "comment",
		"uddi.dhcp_options":        "dhcp_options",
		"uddi.disable_dhcp":        "disable_dhcp",
		"uddi.hostname":            "hostname",
		"uddi.inheritance_parent":  "inheritance_parent",
		"uddi.inheritance_sources": "inheritance_sources",
		"uddi.ip_space":            "ip_space",
		"uddi.match_type":          "match_type",
		"uddi.match_value":         "match_value",
		"uddi.name":                "name",
		"uddi.parent":              "parent",
		"uddi.tags":                "tags",
	},
}
