package dhcp

import "github.com/infobloxopen/terraform-provider-infoblox/internal/core"

// SharednetworkNIOSFieldMap maps infoblox model fields to NIOS struct fields
var SharednetworkNIOSFieldMap = map[string]string{
	"Id":                                  "Ref",
	"NIOS.Authority":                      "Authority",
	"NIOS.Bootfile":                       "Bootfile",
	"NIOS.Bootserver":                     "Bootserver",
	"NIOS.Comment":                        "Comment",
	"NIOS.DdnsGenerateHostname":           "DdnsGenerateHostname",
	"NIOS.DdnsServerAlwaysUpdates":        "DdnsServerAlwaysUpdates",
	"NIOS.DdnsTtl":                        "DdnsTtl",
	"NIOS.DdnsUpdateFixedAddresses":       "DdnsUpdateFixedAddresses",
	"NIOS.DdnsUseOption81":                "DdnsUseOption81",
	"NIOS.DenyBootp":                      "DenyBootp",
	"NIOS.Disable":                        "Disable",
	"NIOS.EnableDdns":                     "EnableDdns",
	"NIOS.EnablePxeLeaseTime":             "EnablePxeLeaseTime",
	"NIOS.IgnoreClientIdentifier":         "IgnoreClientIdentifier",
	"NIOS.IgnoreDhcpOptionListRequest":    "IgnoreDhcpOptionListRequest",
	"NIOS.IgnoreId":                       "IgnoreId",
	"NIOS.IgnoreMacAddresses":             "IgnoreMacAddresses",
	"NIOS.LeaseScavengeTime":              "LeaseScavengeTime",
	"NIOS.LogicFilterRules":               "LogicFilterRules",
	"NIOS.Name":                           "Name",
	"NIOS.NetworkView":                    "NetworkView",
	"NIOS.Networks":                       "Networks",
	"NIOS.Nextserver":                     "Nextserver",
	"NIOS.Options":                        "Options",
	"NIOS.PxeLeaseTime":                   "PxeLeaseTime",
	"NIOS.UpdateDnsOnLeaseRenewal":        "UpdateDnsOnLeaseRenewal",
	"NIOS.UseAuthority":                   "UseAuthority",
	"NIOS.UseBootfile":                    "UseBootfile",
	"NIOS.UseBootserver":                  "UseBootserver",
	"NIOS.UseDdnsGenerateHostname":        "UseDdnsGenerateHostname",
	"NIOS.UseDdnsTtl":                     "UseDdnsTtl",
	"NIOS.UseDdnsUpdateFixedAddresses":    "UseDdnsUpdateFixedAddresses",
	"NIOS.UseDdnsUseOption81":             "UseDdnsUseOption81",
	"NIOS.UseDenyBootp":                   "UseDenyBootp",
	"NIOS.UseEnableDdns":                  "UseEnableDdns",
	"NIOS.UseIgnoreClientIdentifier":      "UseIgnoreClientIdentifier",
	"NIOS.UseIgnoreDhcpOptionListRequest": "UseIgnoreDhcpOptionListRequest",
	"NIOS.UseIgnoreId":                    "UseIgnoreId",
	"NIOS.UseLeaseScavengeTime":           "UseLeaseScavengeTime",
	"NIOS.UseLogicFilterRules":            "UseLogicFilterRules",
	"NIOS.UseNextserver":                  "UseNextserver",
	"NIOS.UseOptions":                     "UseOptions",
	"NIOS.UsePxeLeaseTime":                "UsePxeLeaseTime",
	"NIOS.UseUpdateDnsOnLeaseRenewal":     "UseUpdateDnsOnLeaseRenewal",
}

// TODO: only searchable fields should be included here
// SharednetworkFilterFieldMap maps infoblox filter keys to backend-specific API filter field names
var SharednetworkFilterFieldMap = map[core.BackendType]map[string]string{
	core.BackendNIOS: {
		"id":                                       "_ref",
		"nios.authority":                           "authority",
		"nios.bootfile":                            "bootfile",
		"nios.bootserver":                          "bootserver",
		"nios.comment":                             "comment",
		"nios.ddns_generate_hostname":              "ddns_generate_hostname",
		"nios.ddns_server_always_updates":          "ddns_server_always_updates",
		"nios.ddns_ttl":                            "ddns_ttl",
		"nios.ddns_update_fixed_addresses":         "ddns_update_fixed_addresses",
		"nios.ddns_use_option81":                   "ddns_use_option81",
		"nios.deny_bootp":                          "deny_bootp",
		"nios.disable":                             "disable",
		"nios.enable_ddns":                         "enable_ddns",
		"nios.enable_pxe_lease_time":               "enable_pxe_lease_time",
		"nios.ext_attrs":                           "extattrs",
		"nios.ignore_client_identifier":            "ignore_client_identifier",
		"nios.ignore_dhcp_option_list_request":     "ignore_dhcp_option_list_request",
		"nios.ignore_id":                           "ignore_id",
		"nios.ignore_mac_addresses":                "ignore_mac_addresses",
		"nios.lease_scavenge_time":                 "lease_scavenge_time",
		"nios.logic_filter_rules":                  "logic_filter_rules",
		"nios.name":                                "name",
		"nios.network_view":                        "network_view",
		"nios.networks":                            "networks",
		"nios.nextserver":                          "nextserver",
		"nios.options":                             "options",
		"nios.pxe_lease_time":                      "pxe_lease_time",
		"nios.update_dns_on_lease_renewal":         "update_dns_on_lease_renewal",
		"nios.use_authority":                       "use_authority",
		"nios.use_bootfile":                        "use_bootfile",
		"nios.use_bootserver":                      "use_bootserver",
		"nios.use_ddns_generate_hostname":          "use_ddns_generate_hostname",
		"nios.use_ddns_ttl":                        "use_ddns_ttl",
		"nios.use_ddns_update_fixed_addresses":     "use_ddns_update_fixed_addresses",
		"nios.use_ddns_use_option81":               "use_ddns_use_option81",
		"nios.use_deny_bootp":                      "use_deny_bootp",
		"nios.use_enable_ddns":                     "use_enable_ddns",
		"nios.use_ignore_client_identifier":        "use_ignore_client_identifier",
		"nios.use_ignore_dhcp_option_list_request": "use_ignore_dhcp_option_list_request",
		"nios.use_ignore_id":                       "use_ignore_id",
		"nios.use_lease_scavenge_time":             "use_lease_scavenge_time",
		"nios.use_logic_filter_rules":              "use_logic_filter_rules",
		"nios.use_nextserver":                      "use_nextserver",
		"nios.use_options":                         "use_options",
		"nios.use_pxe_lease_time":                  "use_pxe_lease_time",
		"nios.use_update_dns_on_lease_renewal":     "use_update_dns_on_lease_renewal",
	},
}
