package dtc

import "github.com/infobloxopen/terraform-provider-infoblox/internal/core"

// DtcMonitorHttpNIOSFieldMap maps infoblox model fields to NIOS struct fields
var DtcMonitorHttpNIOSFieldMap = map[string]string{
	"Id":                       "Ref",
	"NIOS.Ciphers":             "Ciphers",
	"NIOS.ClientCert":          "ClientCert",
	"NIOS.Comment":             "Comment",
	"NIOS.ContentCheck":        "ContentCheck",
	"NIOS.ContentCheckInput":   "ContentCheckInput",
	"NIOS.ContentCheckOp":      "ContentCheckOp",
	"NIOS.ContentCheckRegex":   "ContentCheckRegex",
	"NIOS.ContentExtractGroup": "ContentExtractGroup",
	"NIOS.ContentExtractType":  "ContentExtractType",
	"NIOS.ContentExtractValue": "ContentExtractValue",
	"NIOS.EnableSni":           "EnableSni",
	"NIOS.Interval":            "Interval",
	"NIOS.Name":                "Name",
	"NIOS.Port":                "Port",
	"NIOS.Request":             "Request",
	"NIOS.Result":              "Result",
	"NIOS.ResultCode":          "ResultCode",
	"NIOS.RetryDown":           "RetryDown",
	"NIOS.RetryUp":             "RetryUp",
	"NIOS.Secure":              "Secure",
	"NIOS.Timeout":             "Timeout",
	"NIOS.ValidateCert":        "ValidateCert",
}

// DtcMonitorHttpUDDIFieldMap maps infoblox model fields to UDDI struct fields
var DtcMonitorHttpUDDIFieldMap = map[string]string{
	"UDDI.CheckResponseBody":           "CheckResponseBody",
	"UDDI.CheckResponseBodyNegative":   "CheckResponseBodyNegative",
	"UDDI.CheckResponseBodyRegex":      "CheckResponseBodyRegex",
	"UDDI.CheckResponseHeader":         "CheckResponseHeader",
	"UDDI.CheckResponseHeaderNegative": "CheckResponseHeaderNegative",
	"UDDI.CheckResponseHeaderRegexes":  "CheckResponseHeaderRegexes",
	"UDDI.Codes":                       "Codes",
	"UDDI.Comment":                     "Comment",
	"UDDI.Disabled":                    "Disabled",
	"UDDI.Https":                       "Https",
	"UDDI.Interval":                    "Interval",
	"UDDI.Name":                        "Name",
	"UDDI.Port":                        "Port",
	"UDDI.Request":                     "Request",
	"UDDI.RetryDown":                   "RetryDown",
	"UDDI.RetryUp":                     "RetryUp",
	"UDDI.Tags":                        "Tags",
	"UDDI.Timeout":                     "Timeout",
}

// TODO: only searchable fields should be included here
// DtcMonitorHttpFilterFieldMap maps infoblox filter keys to backend-specific API filter field names
var DtcMonitorHttpFilterFieldMap = map[core.BackendType]map[string]string{
	core.BackendNIOS: {
		"id":                         "_ref",
		"nios.ciphers":               "ciphers",
		"nios.client_cert":           "client_cert",
		"nios.comment":               "comment",
		"nios.content_check":         "content_check",
		"nios.content_check_input":   "content_check_input",
		"nios.content_check_op":      "content_check_op",
		"nios.content_check_regex":   "content_check_regex",
		"nios.content_extract_group": "content_extract_group",
		"nios.content_extract_type":  "content_extract_type",
		"nios.content_extract_value": "content_extract_value",
		"nios.enable_sni":            "enable_sni",
		"nios.ext_attrs":             "extattrs",
		"nios.interval":              "interval",
		"nios.name":                  "name",
		"nios.port":                  "port",
		"nios.request":               "request",
		"nios.result":                "result",
		"nios.result_code":           "result_code",
		"nios.retry_down":            "retry_down",
		"nios.retry_up":              "retry_up",
		"nios.secure":                "secure",
		"nios.timeout":               "timeout",
		"nios.validate_cert":         "validate_cert",
	},
	core.BackendUDDI: {
		"uddi.check_response_body":            "check_response_body",
		"uddi.check_response_body_negative":   "check_response_body_negative",
		"uddi.check_response_body_regex":      "check_response_body_regex",
		"uddi.check_response_header":          "check_response_header",
		"uddi.check_response_header_negative": "check_response_header_negative",
		"uddi.check_response_header_regexes":  "check_response_header_regexes",
		"uddi.codes":                          "codes",
		"uddi.comment":                        "comment",
		"uddi.disabled":                       "disabled",
		"uddi.https":                          "https",
		"uddi.interval":                       "interval",
		"uddi.name":                           "name",
		"uddi.port":                           "port",
		"uddi.request":                        "request",
		"uddi.retry_down":                     "retry_down",
		"uddi.retry_up":                       "retry_up",
		"uddi.tags":                           "tags",
		"uddi.timeout":                        "timeout",
	},
}
