apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Cloud Marketplace Terraform Module
    source:
      repo: https://github.com/infobloxopen/terraform-provider-infoblox.git 
      sourceType: git
      dir: /nios-public-cloud-marketplace/gcp/nios-cli-tf/
    version: 0.0.1
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
    softwareGroups:
      - type: SG_OS
        software:
          - title: Ubuntu
            version: "22.04"
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instance.
        varType: string
        required: true
      - name: source_image
        description: The image name for the disk for the VM instance.
        varType: string
        defaultValue: projects/infoblox-public-436917/global/images/infoblox-nios-906-53318-byol
      - name: zone
        description: (Optional) The zone that the machine should be created in. If it is not provided, the provider zone is used.
        varType: string
        defaultValue: us-central1-a
      - name: machine_type
        description: The machine type to create, e.g. e2-small
        varType: string
        defaultValue: n1-hightmem-8
      - name: boot_disk_type
        description: The boot disk type for the VM instance.
        varType: string
        defaultValue: pd-ssd
      - name: boot_disk_size
        description: The boot disk size for the VM instance in GBs
        varType: number
        defaultValue: 500
      - name: networks
        description: The network name to attach the VM instance.
        varType: list(string)
        defaultValue:
          - default
      - name: sub_networks
        description: The sub network name to attach the VM instance.
        varType: list(string)
        defaultValue: []
      - name: external_ips
        description: The external IPs assigned to the VM for public access.
        varType: list(string)
        defaultValue:
          - EPHEMERAL
      - name: enable_cloud_api
        description: Allow full access to all of Google Cloud Platform APIs on the VM
        varType: bool
        defaultValue: true
      - name: labels
        description: (Optional) A map of key/value in string format to assign to the instance.
        varType: string
        defaultValue: "{}"
      - name: tags
        description: (Optional) A list of network tags to attach to the instance.
        varType: list(string)
        defaultValue: []
      - name: metadata
        description: (Optional) Metadata key/value in string format to make available from within the VM instance.
        varType: string
        defaultValue: "{\"google-logging-enable\":\"0\",\"google-monitoring-enable\":\"0\", \"user-data\":\"#infoblox-config\"}"
    outputs:
      - name: instance_machine_type
        description: Machine type for the compute instance.
      - name: instance_nat_ip
        description: External IP of the compute instance.
      - name: instance_network
        description: Self-link for the network of the compute instance.
      - name: instance_self_link
        description: Self-link for the compute instance.
      - name: instance_zone
        description: Zone for the compute instance.

