package dns

import "github.com/infobloxopen/terraform-provider-infoblox/internal/core"

// DnsServerUDDIFieldMap maps infoblox model fields to UDDI struct fields
var DnsServerUDDIFieldMap = map[string]string{
	"UDDI.AddEdnsOptionInOutgoingQuery":                "AddEdnsOptionInOutgoingQuery",
	"UDDI.AutoSortViews":                               "AutoSortViews",
	"UDDI.Comment":                                     "Comment",
	"UDDI.CustomRootNs":                                "CustomRootNs",
	"UDDI.CustomRootNsEnabled":                         "CustomRootNsEnabled",
	"UDDI.DnssecEnableValidation":                      "DnssecEnableValidation",
	"UDDI.DnssecEnabled":                               "DnssecEnabled",
	"UDDI.DnssecTrustAnchors":                          "DnssecTrustAnchors",
	"UDDI.DnssecValidateExpiry":                        "DnssecValidateExpiry",
	"UDDI.EcsEnabled":                                  "EcsEnabled",
	"UDDI.EcsForwarding":                               "EcsForwarding",
	"UDDI.EcsPrefixV4":                                 "EcsPrefixV4",
	"UDDI.EcsPrefixV6":                                 "EcsPrefixV6",
	"UDDI.EcsZones":                                    "EcsZones",
	"UDDI.FilterAaaaAcl":                               "FilterAaaaAcl",
	"UDDI.FilterAaaaOnV4":                              "FilterAaaaOnV4",
	"UDDI.Forwarders":                                  "Forwarders",
	"UDDI.ForwardersOnly":                              "ForwardersOnly",
	"UDDI.GssTsigEnabled":                              "GssTsigEnabled",
	"UDDI.InheritanceSources":                          "InheritanceSources",
	"UDDI.KerberosKeys":                                "KerberosKeys",
	"UDDI.LameTtl":                                     "LameTtl",
	"UDDI.LogQueryResponse":                            "LogQueryResponse",
	"UDDI.MatchRecursiveOnly":                          "MatchRecursiveOnly",
	"UDDI.MaxCacheTtl":                                 "MaxCacheTtl",
	"UDDI.MaxNegativeTtl":                              "MaxNegativeTtl",
	"UDDI.MinimalResponses":                            "MinimalResponses",
	"UDDI.Name":                                        "Name",
	"UDDI.Notify":                                      "Notify",
	"UDDI.QueryAcl":                                    "QueryAcl",
	"UDDI.QueryPort":                                   "QueryPort",
	"UDDI.RecursionAcl":                                "RecursionAcl",
	"UDDI.RecursionEnabled":                            "RecursionEnabled",
	"UDDI.RecursiveClients":                            "RecursiveClients",
	"UDDI.ResolverQueryTimeout":                        "ResolverQueryTimeout",
	"UDDI.SecondaryAxfrQueryLimit":                     "SecondaryAxfrQueryLimit",
	"UDDI.SecondarySoaQueryLimit":                      "SecondarySoaQueryLimit",
	"UDDI.SortList":                                    "SortList",
	"UDDI.SynthesizeAddressRecordsFromHttps":           "SynthesizeAddressRecordsFromHttps",
	"UDDI.Tags":                                        "Tags",
	"UDDI.TransferAcl":                                 "TransferAcl",
	"UDDI.UpdateAcl":                                   "UpdateAcl",
	"UDDI.UseForwardersForSubzones":                    "UseForwardersForSubzones",
	"UDDI.UseRootForwardersForLocalResolutionWithB1td": "UseRootForwardersForLocalResolutionWithB1td",
	"UDDI.Views":                                       "Views",
}

// TODO: only searchable fields should be included here
// DnsServerFilterFieldMap maps infoblox filter keys to backend-specific API filter field names
var DnsServerFilterFieldMap = map[core.BackendType]map[string]string{
	core.BackendUDDI: {
		"uddi.add_edns_option_in_outgoing_query":     "add_edns_option_in_outgoing_query",
		"uddi.auto_sort_views":                       "auto_sort_views",
		"uddi.comment":                               "comment",
		"uddi.custom_root_ns":                        "custom_root_ns",
		"uddi.custom_root_ns_enabled":                "custom_root_ns_enabled",
		"uddi.dnssec_enable_validation":              "dnssec_enable_validation",
		"uddi.dnssec_enabled":                        "dnssec_enabled",
		"uddi.dnssec_trust_anchors":                  "dnssec_trust_anchors",
		"uddi.dnssec_validate_expiry":                "dnssec_validate_expiry",
		"uddi.ecs_enabled":                           "ecs_enabled",
		"uddi.ecs_forwarding":                        "ecs_forwarding",
		"uddi.ecs_prefix_v4":                         "ecs_prefix_v4",
		"uddi.ecs_prefix_v6":                         "ecs_prefix_v6",
		"uddi.ecs_zones":                             "ecs_zones",
		"uddi.filter_aaaa_acl":                       "filter_aaaa_acl",
		"uddi.filter_aaaa_on_v4":                     "filter_aaaa_on_v4",
		"uddi.forwarders":                            "forwarders",
		"uddi.forwarders_only":                       "forwarders_only",
		"uddi.gss_tsig_enabled":                      "gss_tsig_enabled",
		"uddi.inheritance_sources":                   "inheritance_sources",
		"uddi.kerberos_keys":                         "kerberos_keys",
		"uddi.lame_ttl":                              "lame_ttl",
		"uddi.log_query_response":                    "log_query_response",
		"uddi.match_recursive_only":                  "match_recursive_only",
		"uddi.max_cache_ttl":                         "max_cache_ttl",
		"uddi.max_negative_ttl":                      "max_negative_ttl",
		"uddi.minimal_responses":                     "minimal_responses",
		"uddi.name":                                  "name",
		"uddi.notify":                                "notify",
		"uddi.query_acl":                             "query_acl",
		"uddi.query_port":                            "query_port",
		"uddi.recursion_acl":                         "recursion_acl",
		"uddi.recursion_enabled":                     "recursion_enabled",
		"uddi.recursive_clients":                     "recursive_clients",
		"uddi.resolver_query_timeout":                "resolver_query_timeout",
		"uddi.secondary_axfr_query_limit":            "secondary_axfr_query_limit",
		"uddi.secondary_soa_query_limit":             "secondary_soa_query_limit",
		"uddi.sort_list":                             "sort_list",
		"uddi.synthesize_address_records_from_https": "synthesize_address_records_from_https",
		"uddi.tags":                                  "tags",
		"uddi.transfer_acl":                          "transfer_acl",
		"uddi.update_acl":                            "update_acl",
		"uddi.use_forwarders_for_subzones":           "use_forwarders_for_subzones",
		"uddi.use_root_forwarders_for_local_resolution_with_b1td": "use_root_forwarders_for_local_resolution_with_b1td",
		"uddi.views": "views",
	},
}
