package dns

import "github.com/infobloxopen/terraform-provider-infoblox/internal/core"

// ZoneRpNIOSFieldMap maps infoblox model fields to NIOS struct fields
var ZoneRpNIOSFieldMap = map[string]string{
	"Id":                                    "Ref",
	"NIOS.Comment":                          "Comment",
	"NIOS.Disable":                          "Disable",
	"NIOS.ExternalPrimaries":                "ExternalPrimaries",
	"NIOS.ExternalSecondaries":              "ExternalSecondaries",
	"NIOS.FireeyeRuleMapping":               "FireeyeRuleMapping",
	"NIOS.Fqdn":                             "Fqdn",
	"NIOS.GridPrimary":                      "GridPrimary",
	"NIOS.GridSecondaries":                  "GridSecondaries",
	"NIOS.Locked":                           "Locked",
	"NIOS.LogRpz":                           "LogRpz",
	"NIOS.MemberSoaMnames":                  "MemberSoaMnames",
	"NIOS.NsGroup":                          "NsGroup",
	"NIOS.Prefix":                           "Prefix",
	"NIOS.RecordNamePolicy":                 "RecordNamePolicy",
	"NIOS.RpzDropIpRuleEnabled":             "RpzDropIpRuleEnabled",
	"NIOS.RpzDropIpRuleMinPrefixLengthIpv4": "RpzDropIpRuleMinPrefixLengthIpv4",
	"NIOS.RpzDropIpRuleMinPrefixLengthIpv6": "RpzDropIpRuleMinPrefixLengthIpv6",
	"NIOS.RpzPolicy":                        "RpzPolicy",
	"NIOS.RpzSeverity":                      "RpzSeverity",
	"NIOS.RpzType":                          "RpzType",
	"NIOS.SetSoaSerialNumber":               "SetSoaSerialNumber",
	"NIOS.SoaDefaultTtl":                    "SoaDefaultTtl",
	"NIOS.SoaEmail":                         "SoaEmail",
	"NIOS.SoaExpire":                        "SoaExpire",
	"NIOS.SoaNegativeTtl":                   "SoaNegativeTtl",
	"NIOS.SoaRefresh":                       "SoaRefresh",
	"NIOS.SoaRetry":                         "SoaRetry",
	"NIOS.SoaSerialNumber":                  "SoaSerial",
	"NIOS.SubstituteName":                   "SubstituteName",
	"NIOS.UseExternalPrimary":               "UseExternalPrimary",
	"NIOS.UseGridZoneTimer":                 "UseGridZoneTimer",
	"NIOS.UseLogRpz":                        "UseLogRpz",
	"NIOS.UseRecordNamePolicy":              "UseRecordNamePolicy",
	"NIOS.UseRpzDropIpRule":                 "UseRpzDropIpRule",
	"NIOS.UseSoaEmail":                      "UseSoaEmail",
	"NIOS.View":                             "View",
}

// TODO: only searchable fields should be included here
// ZoneRpFilterFieldMap maps infoblox filter keys to backend-specific API filter field names
var ZoneRpFilterFieldMap = map[core.BackendType]map[string]string{
	core.BackendNIOS: {
		"id":                            "_ref",
		"nios.comment":                  "comment",
		"nios.disable":                  "disable",
		"nios.ext_attrs":                "extattrs",
		"nios.external_primaries":       "external_primaries",
		"nios.external_secondaries":     "external_secondaries",
		"nios.fireeye_rule_mapping":     "fireeye_rule_mapping",
		"nios.fqdn":                     "fqdn",
		"nios.grid_primary":             "grid_primary",
		"nios.grid_secondaries":         "grid_secondaries",
		"nios.locked":                   "locked",
		"nios.log_rpz":                  "log_rpz",
		"nios.member_soa_mnames":        "member_soa_mnames",
		"nios.ns_group":                 "ns_group",
		"nios.prefix":                   "prefix",
		"nios.record_name_policy":       "record_name_policy",
		"nios.rpz_drop_ip_rule_enabled": "rpz_drop_ip_rule_enabled",
		"nios.rpz_drop_ip_rule_min_prefix_length_ipv4": "rpz_drop_ip_rule_min_prefix_length_ipv4",
		"nios.rpz_drop_ip_rule_min_prefix_length_ipv6": "rpz_drop_ip_rule_min_prefix_length_ipv6",
		"nios.rpz_policy":             "rpz_policy",
		"nios.rpz_severity":           "rpz_severity",
		"nios.rpz_type":               "rpz_type",
		"nios.set_soa_serial_number":  "set_soa_serial_number",
		"nios.soa_default_ttl":        "soa_default_ttl",
		"nios.soa_email":              "soa_email",
		"nios.soa_expire":             "soa_expire",
		"nios.soa_negative_ttl":       "soa_negative_ttl",
		"nios.soa_refresh":            "soa_refresh",
		"nios.soa_retry":              "soa_retry",
		"nios.soa_serial_number":      "soa_serial_number",
		"nios.substitute_name":        "substitute_name",
		"nios.use_external_primary":   "use_external_primary",
		"nios.use_grid_zone_timer":    "use_grid_zone_timer",
		"nios.use_log_rpz":            "use_log_rpz",
		"nios.use_record_name_policy": "use_record_name_policy",
		"nios.use_rpz_drop_ip_rule":   "use_rpz_drop_ip_rule",
		"nios.use_soa_email":          "use_soa_email",
		"nios.view":                   "view",
	},
}
